server:
  #端口
  port: 8080


spring:
  # 控制台banner
  output:
    ansi:
      enabled: always

  datasource:
    ########################后续配置多数据源
    #数据源配置，使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oa_restart?serverTimezone=Asia/Shanghai
    username: root
    password: root

    druid:
      # 连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20

      # 连接等待时间
      max-wait: 30000

      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000

      # 用来检测连接是否有效的sql，要求是一个查询语句
      validation-query: select '1' from dual

      # 建议配置为true，不影响性能，并且保证安全性。
      # 如果空闲时间大于timeBetweenEvictionRunsMills，执行validationQuery检测连接是否有效
      test-while-idle: true
      # 申请连接时和归还连接时执行validationQuery检测连接是否有效，开通配置会降低性能
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache并且指定每个连接上PSCache的大小
      # 此选项可理解为是否缓存PreparedStatement，PS即PreparedStatement。
      # PSCache对支持游标的数据库性能提升巨大，比如Oracle，MySQL建议关闭。
      pool-prepared-statements: false
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall' 用于防火墙
      filters: stat
      # Spring监控AOP切入点，如x.y.z.service.*，配置多个用 英文逗号 ',' 分隔
      aop-patterns: cn.ean.oa_emp.service.*,cn.ean.oa_emp.controller.*

      # WebStatFilter配置
      web-stat-filter:
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤的格式
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      # StatViewServlet配置
      stat-view-servlet:
        enabled: true
        # 访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
        # 是否能够重置数据
        reset-enable: false
        # 需要账号密码才能访问控制台
        login-username: druid
        login-password: druid123
        # IP白名单
        # allow: 127.0.0.1
        # IP黑名单（共同存在时，deny优先于allow）
        # deny: 192.168.1.218

      # 配置StatFilter
      filter:
        stat:
          log-slow-sql: true

mybatis-plus:
  # type-aliases扫描路径（容易报错）
#  type-aliases-package: cn.ean.oa_emp.model.po
  # mapper xml实现扫描路径
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: false


# Mybatis SQL打印（方法接口所在的，不是xml文件的包）
logging:
  level:
    cn.ean.oa_emp.mapper: debug

jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT加解签名使用的密钥，后32位为前面内容MD5加密后的密文
  secret: oa-emp-secret-B9C1B02785FA44DC1064AAC47962FD08
  # JWT的超期限时间 (60*60*24)
  expiration: 604800
  # JWT负载中拿到开头
  tokenHead: Bearer